[build]
  command = "npm run build"
  publish = "dist"

# Set OPENAI_API_KEY as a build environment variable in Netlify dashboard

[build.environment]
  NODE_VERSION = "20"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200