name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
      - name: Create index.html in dist root
        run: |
          # Check if index.html exists at the root of dist
          if [ ! -f dist/index.html ]; then
            # If it doesn't exist, let's see what files are in the dist directory
            ls -la dist/
            # Let's check if it might be in a client subdirectory
            if [ -f dist/client/index.html ]; then
              # Copy index.html to dist root
              cp dist/client/index.html dist/
              echo "Copied index.html from dist/client to dist root"
            fi
          fi
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
